# Generated by Django 5.2.5 on 2025-09-04 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(0, 'Beginning'), (1, 'Copy'), (2, 'Thief'), (3, 'Thief Copy'), (4, 'Brothers'), (5, 'Seer'), (6, 'Seer Copy'), (7, 'Brawler'), (8, 'Brawler Copy'), (9, 'Drunkard'), (10, 'Drunkard Copy'), (11, 'Witch'), (12, 'Witch Copy'), (13, 'Milkman'), (14, 'Milkman Copy'), (15, 'Shooting'), (16, 'Finished')])),
                ('copied_role', models.CharField(choices=[('copy', 'Copy'), ('thief', 'Thief'), ('brothers_1', 'Brothers 1'), ('brothers_2', 'Brothers 2'), ('seer', 'Seer'), ('brawler', 'Brawler'), ('drunkard', 'Drunkard'), ('witch', 'Witch'), ('milkman', 'Milkman'), ('mafia', 'Mafia'), ('suicide', 'Suicide')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(0, 'Beginning'), (1, 'Copy'), (2, 'Thief'), (3, 'Thief Copy'), (4, 'Brothers'), (5, 'Seer'), (6, 'Seer Copy'), (7, 'Brawler'), (8, 'Brawler Copy'), (9, 'Drunkard'), (10, 'Drunkard Copy'), (11, 'Witch'), (12, 'Witch Copy'), (13, 'Milkman'), (14, 'Milkman Copy'), (15, 'Shooting'), (16, 'Finished')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cards', models.JSONField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_move_time', models.IntegerField(default=5)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='GameStageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='game.gamestate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'state'), name='unique_user_state_read')],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_to_show', models.JSONField(blank=True)),
                ('swap_card_a', models.IntegerField(null=True)),
                ('swap_card_b', models.IntegerField(null=True)),
                ('game_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='game.gamestate')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('swap_card_a__isnull', True), ('swap_card_b__isnull', True)), models.Q(('swap_card_a__isnull', False), ('swap_card_b__isnull', False)), _connector='OR'), name='both_cards_null_or_not_null')],
            },
        ),
    ]
