# Generated by Django 5.2.5 on 2025-09-05 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.room'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(('swap_card_a', models.F('swap_card_b')), _negated=True), name='cards_to_swap_not_equal'),
        ),
    ]
