# Generated by Django 5.2.5 on 2025-09-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_cardshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardshot',
            name='shot_by',
        ),
        migrations.AddField(
            model_name='cardshot',
            name='shooter_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
